version: 2

models:
  - name: user_data
    description: "Userdata from fantasy"
    columns:
      - name: department_id
        description: "The primary key for this table"
        tests:
          - not_null

  - name: user_data_dal
    description: "user data with dal lookup data"
    columns:
      - name: teamname
        description: "referenced column from dal and it cannot be null"
        tests:
          - not_null
